describe('BL UI Components - BLUISimpleSelect', function () {
  it.only('Verify BL UI Simple Select', function () {
    cy.LaunchURLandLogin()
    cy.get('#components-simple-select')
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
    cy.get('#components-simple-select--docs')
      .should('be.visible')
      .click({ force: true })
    cy.wait(1000)

    //ID
    cy.iframe('#storybook-preview-iframe')
      .find('#control-id')
      .type('{backspace}')
      .clear()
      .type('Cypress Automation')
    cy.wait(1000)

    //Minus(-) icon
    cy.iframe('#storybook-preview-iframe')
      .find(
        'table > tbody > tr:nth-child(3) > td:nth-child(4) > div > div > div > span > svg:nth-child(5)'
      )
      .click({ force: true })
    cy.wait(1000)
    cy.iframe('#storybook-preview-iframe')
      .find('#set-options')
      .click({ force: true })
    cy.wait(1000)
    //Add(+) icon
    cy.iframe('#storybook-preview-iframe')
      .find('[class="rejt-plus-menu css-k52l0m"]')
      .click({ force: true })
    //check1
    cy.iframe('#storybook-preview-iframe')
      .xpath(
        "//*[@id='storybook-docs']/div/div/div[2]/table/tbody/tr[3]/td[4]/div/div/div/span[2]/div/span/input[1]"
      )
      .type('1')
    cy.iframe('#storybook-preview-iframe')
      .find('[class="css-177mwmb"]')
      .type('Check1')
    cy.wait(1000)
    cy.iframe('#storybook-preview-iframe')
      .find('[class="css-enyqhd"]')
      .click({ force: true })
    //Check2
    cy.iframe('#storybook-preview-iframe')
      .find('[class="rejt-plus-menu css-k52l0m"]')
      .click({ force: true })
    cy.iframe('#storybook-preview-iframe')
      .find('[class="css-1trcvz8"]')
      .type('2')
    cy.iframe('#storybook-preview-iframe')
      .find('[class="css-177mwmb"]')
      .type('Check2')
    cy.wait(1000)
    cy.iframe('#storybook-preview-iframe')
      .find('[class="css-enyqhd"]')
      .click({ force: true })
    //Check3
    cy.iframe('#storybook-preview-iframe')
      .find('[class="rejt-plus-menu css-k52l0m"]')
      .click({ force: true })
    cy.iframe('#storybook-preview-iframe')
      .find('[class="css-1trcvz8"]')
      .type('3')
    cy.iframe('#storybook-preview-iframe')
      .find('[class="css-177mwmb"]')
      .type('Check3')
    cy.wait(1000)
    cy.iframe('#storybook-preview-iframe')
      .find('[class="css-enyqhd"]')
      .click({ force: true })
    //Check4
    cy.iframe('#storybook-preview-iframe')
      .find('[class="rejt-plus-menu css-k52l0m"]')
      .click({ force: true })
    cy.iframe('#storybook-preview-iframe')
      .find('[class="css-1trcvz8"]')
      .type('4')
    cy.iframe('#storybook-preview-iframe')
      .find('[class="css-177mwmb"]')
      .type('Check4')
    // cy.wait(1000)
    // cy.Scrolltop()
    // cy.iframe('#storybook-preview-iframe').xpath("//*[@id='anuto']/div/button").click({force:true})
    cy.wait(2000)

    //Check label
    cy.iframe('#storybook-preview-iframe')
      .find('#set-label')
      .should('be.visible')
      .click({ force: true })
    cy.iframe('#storybook-preview-iframe')
      .find('#control-label')
      .type('Cypress Automation')
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(2000)

    //Check Placeholder
    cy.iframe('#storybook-preview-iframe')
      .find('#set-placeholder')
      .should('be.visible')
      .click({ force: true })
    cy.iframe('#storybook-preview-iframe')
      .find('#control-placeholder')
      .type('Automation')
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(2000)

    //Check disabled
    cy.iframe('#storybook-preview-iframe')
      .find('#set-disabled')
      .should('be.visible')
      .click({ force: true })
    cy.iframe('#storybook-preview-iframe').find('#control-disabled').click()
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(1000)
    cy.iframe('#storybook-preview-iframe').find('#control-disabled').click()
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(2000)

    //Check MaxHeightPx
    cy.iframe('#storybook-preview-iframe')
      .find('#set-maxHeightPx')
      .should('be.visible')
      .click({ force: true })
    cy.iframe('#storybook-preview-iframe')
      .find('#control-maxHeightPx')
      .type('{backspace}')
      .clear()
      .type('150')
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(1000)
    //cy.iframe('#storybook-preview-iframe').xpath("//*[@id='anuto']/div/button").should('be.visible').click({force:true})
    //cy.wait(2000)

    //Searchable
    cy.iframe('#storybook-preview-iframe')
      .find('#set-searchable')
      .should('be.visible')
      .click({ force: true })
    cy.wait(1000)
    cy.iframe('#storybook-preview-iframe')
      .find('#control-searchable')
      .click({ force: true })
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(2000)

    //Allowclear
    cy.iframe('#storybook-preview-iframe')
      .find('#set-allowClear')
      .should('be.visible')
      .click({ force: true })
    cy.wait(1000)
    cy.iframe('#storybook-preview-iframe')
      .find('#control-allowClear')
      .click({ force: true })
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(2000)

    //value
    cy.iframe('#storybook-preview-iframe')
      .find('#set-value')
      .should('be.visible')
      .click({ force: true })
    cy.wait(1000)
    cy.iframe('#storybook-preview-iframe').find('#control-value').type('100')
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(2000)
  })

  //Default
  it.only('Verify Default Tab', function () {
    cy.Reload()
    cy.get('#components-simple-select')
      .should('be.visible')
      .click({ force: true })
    cy.wait(1000)
    cy.get('#components-simple-select--default')
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })

  //Searchable
  it('Verify Searchable Tab', function () {
    cy.Reload()
    cy.get('#components-simple-select')
      .should('be.visible')
      .click({ force: true })
    cy.wait(1000)
    cy.get('#components-simple-select--searchable')
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })

  //Disabled
  it.only('Verify Disabled Tab', function () {
    cy.Reload()
    cy.get('#components-simple-select')
      .should('be.visible')
      .click({ force: true })
    cy.wait(1000)
    cy.get('#components-simple-select--disabled')
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })

  //With Label
  it.only('Verify With Label Tab', function () {
    cy.Reload()
    cy.get('#components-simple-select')
      .should('be.visible')
      .click({ force: true })
    cy.wait(1000)
    cy.get('#components-simple-select--with-label')
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })

  //With Place Holder
  it.only('Verify With Place Holder Tab', function () {
    cy.Reload()
    cy.get('#components-simple-select')
      .should('be.visible')
      .click({ force: true })
    cy.wait(1000)
    cy.get('#components-simple-select--with-place-holder')
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })

  //With Shorter Max Height
  it.only('Verify With Shorter Max Height Tab', function () {
    cy.Reload()
    cy.get('#components-simple-select')
      .should('be.visible')
      .click({ force: true })
    cy.wait(1000)
    cy.get('#components-simple-select--with-shorter-max-height')
      .should('be.visible')
      .click({ force: true })
    cy.wait(1000)
    cy.iframe('#storybook-preview-iframe')
      .find('#sample-custom-select > div > button > img')
      .click({ force: true })
    cy.wait(2000)
  })

  //With Clear Options Enabled
  it.only('Verify With Clear Options Enabled Tab', function () {
    cy.Reload()
    cy.get('#components-simple-select')
      .should('be.visible')
      .click({ force: true })
    cy.wait(1000)
    cy.get('#components-simple-select--with-clear-options-enabled')
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })

  //Disabled With Label And Place Holder
  it.only('Verify Disabled With Label And Place Holder Tab', function () {
    cy.Reload()
    cy.get('#components-simple-select')
      .should('be.visible')
      .click({ force: true })
    cy.wait(1000)
    cy.get('#components-simple-select--disabled-with-label-and-place-holder')
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })

  //Custom List Implementation
  it.only('Verify Custom List Implementation Tab', function () {
    cy.Reload()
    cy.get('#components-simple-select')
      .should('be.visible')
      .click({ force: true })
    cy.wait(1000)
    cy.get('#components-simple-select--custom-list-implementation')
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })
})
