describe('BL UI Components - BLUIButton', function () {
  it('Verify BL UI Button', function () {
    cy.LaunchURLandLogin()
    cy.get('#components-button').should('be.visible').click({ force: true })
    cy.wait(2000)
    cy.get('#components-button--docs')
      .should('be.visible')
      .click({ force: true })
    cy.wait(1000)
    //Background
    cy.iframe('#storybook-preview-iframe')
      .find('#control-background')
      .select('Blue 600')
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(1000)
    cy.iframe('#storybook-preview-iframe')
      .find('#control-background')
      .select('Red 600')
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(1000)
    cy.iframe('#storybook-preview-iframe')
      .find('#control-background')
      .select('Gray 600')
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(1000)
    cy.iframe('#storybook-preview-iframe')
      .find('#control-background')
      .select('Green 600')
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(2000)

    //Label
    cy.iframe('#storybook-preview-iframe')
      .find('#control-label')
      .type('{backspace}')
      .clear()
      .type('Cypress Automation')
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(2000)

    //Label long Text
    cy.iframe('#storybook-preview-iframe')
      .find('#control-label')
      .type('{backspace}')
      .clear()
      .type(
        'Cypress Automation Test checking for Label In BL UI Button Functionality Script'
      )
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(2000)

    //Label Empty
    cy.iframe('#storybook-preview-iframe')
      .find('#control-label')
      .type('{backspace}')
      .clear()
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(2000)

    //Variant
    cy.iframe('#storybook-preview-iframe')
      .find('#control-variant')
      .select('Default')
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(1000)
    cy.iframe('#storybook-preview-iframe')
      .find('#control-variant')
      .select('Default Quiet')
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(1000)
    cy.iframe('#storybook-preview-iframe')
      .find('#control-variant')
      .select('Primary')
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(1000)
    cy.iframe('#storybook-preview-iframe')
      .find('#control-variant')
      .select('Primary Quiet')
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(2000)

    //IsDiabled
    cy.iframe('#storybook-preview-iframe')
      .find('#control-isDisabled')
      .should('be.visible')
      .click({ force: true })
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(1000) //True
    cy.iframe('#storybook-preview-iframe')
      .find('#control-isDisabled')
      .should('be.visible')
      .click({ force: true })
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(2000) //False

    //Loading
    cy.iframe('#storybook-preview-iframe')
      .find('#control-loading')
      .should('be.visible')
      .click({ force: true })
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(1000) //True
    cy.iframe('#storybook-preview-iframe')
      .find('#control-loading')
      .should('be.visible')
      .click({ force: true })
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(1000) //False

    // //FullWidth
    cy.iframe('#storybook-preview-iframe')
      .find('#control-fullWidth')
      .should('be.visible')
      .click({ force: true })
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(1000) //True
    cy.iframe('#storybook-preview-iframe')
      .find('#control-fullWidth')
      .should('be.visible')
      .click({ force: true })
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(1000) //False

    //icon
    cy.iframe('#storybook-preview-iframe')
      .find('#control-icon')
      .select('Chevron Down')
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(1000)
    cy.iframe('#storybook-preview-iframe').find('#control-icon').select('Info')
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(1000)
    cy.iframe('#storybook-preview-iframe').find('#control-icon').select('Eye')
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(1000)
    cy.iframe('#storybook-preview-iframe')
      .find('#control-icon')
      .select('EyeSlash')
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(1000)
    cy.iframe('#storybook-preview-iframe').find('#control-icon').select('Globe')
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(1000)
    cy.iframe('#storybook-preview-iframe')
      .find('#control-icon')
      .select('Search')
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(1000)
    cy.iframe('#storybook-preview-iframe')
      .find('#control-icon')
      .select('settings')
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(1000)
    cy.iframe('#storybook-preview-iframe')
      .find('#control-icon')
      .select('Chevron Down')
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(2000)

    //icon
    cy.iframe('#storybook-preview-iframe')
      .find('#control-appendIcon')
      .select('Chevron Down')
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(1000)
    cy.iframe('#storybook-preview-iframe')
      .find('#control-appendIcon')
      .select('Info')
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(1000)
    cy.iframe('#storybook-preview-iframe')
      .find('#control-appendIcon')
      .select('Eye')
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(1000)
    cy.iframe('#storybook-preview-iframe')
      .find('#control-appendIcon')
      .select('EyeSlash')
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(1000)
    cy.iframe('#storybook-preview-iframe')
      .find('#control-appendIcon')
      .select('Globe')
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(1000)
    cy.iframe('#storybook-preview-iframe')
      .find('#control-appendIcon')
      .select('Search')
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(1000)
    cy.iframe('#storybook-preview-iframe')
      .find('#control-appendIcon')
      .select('settings')
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(2000)

    //iconOnlySize
    cy.iframe('#storybook-preview-iframe')
      .find('#control-iconOnlySize')
      .select('Medium')
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(1000)
    cy.iframe('#storybook-preview-iframe')
      .find('#control-iconOnlySize')
      .select('Small')
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(2000)

    //SplitButton
    cy.iframe('#storybook-preview-iframe')
      .find('#control-splitButton')
      .select('Left')
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(1000)
    cy.iframe('#storybook-preview-iframe')
      .find('#control-splitButton')
      .select('Right')
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(1000)
    cy.iframe('#storybook-preview-iframe')
      .find('#control-splitButton')
      .select('both')
    cy.wait(1000)
    cy.Scrolltop()
    cy.wait(2000)
  })

  //Default
  it('Verify Default Tab', function () {
    cy.Reload()
    cy.get('#components-button').should('be.visible').click({ force: true })
    cy.wait(2000)
    cy.get('#components-button--default')
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })

  //Default Button
  it('Verify Default Button Tab', function () {
    cy.Reload()
    cy.get('#components-button').should('be.visible').click({ force: true })
    cy.wait(2000)
    cy.get('#components-button--default-button')
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })

  //Default Quiet Button
  it('Verify Default Quiet Button Tab', function () {
    cy.Reload()
    cy.get('#components-button').should('be.visible').click({ force: true })
    cy.wait(2000)
    cy.get('#components-button--default-quiet-button')
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })

  //Primary Blue
  it('Verify Primary Blue Tab', function () {
    cy.Reload()
    cy.get('#components-button').should('be.visible').click({ force: true })
    cy.wait(2000)
    cy.get('#components-button--primary-blue')
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })

  //Primary Blue Disabled
  it('Verify Primary Blue Disabled Tab', function () {
    cy.Reload()
    cy.get('#components-button').should('be.visible').click({ force: true })
    cy.wait(2000)
    cy.get('#components-button--primary-blue-disabled')
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })

  //Primary Red
  it('Verify Primary Red Tab', function () {
    cy.Reload()
    cy.get('#components-button').should('be.visible').click({ force: true })
    cy.wait(2000)
    cy.get('#components-button--primary-red')
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })

  //Primary Red Disabled
  it('Verify Primary Red Disabled Tab', function () {
    cy.Reload()
    cy.get('#components-button').should('be.visible').click({ force: true })
    cy.wait(2000)
    cy.get('#components-button--primary-red-disabled')
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })

  //Primary Green
  it('Verify Primary Green Tab', function () {
    cy.Reload()
    cy.get('#components-button').should('be.visible').click({ force: true })
    cy.wait(2000)
    cy.get('#components-button--primary-green')
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })

  //Primary Green Disabled
  it('Verify Primary Green Disabled Tab', function () {
    cy.Reload()
    cy.get('#components-button').should('be.visible').click({ force: true })
    cy.wait(2000)
    cy.get('#components-button--primary-green-disabled')
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })

  //Primary Quiet Blue
  it('Verify Primary Quiet Blue Tab', function () {
    cy.Reload()
    cy.get('#components-button').should('be.visible').click({ force: true })
    cy.wait(2000)
    cy.get('#components-button--primary-quiet-blue')
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })

  //Primary Quiet Blue Disabled
  it('Verify Primary Quiet Blue Disabled Tab', function () {
    cy.Reload()
    cy.get('#components-button').should('be.visible').click({ force: true })
    cy.wait(2000)
    cy.get('#components-button--primary-quiet-blue-disabled')
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })

  //Primary Quiet Red
  it('Verify Primary Quiet red Tab', function () {
    cy.Reload()
    cy.get('#components-button').should('be.visible').click({ force: true })
    cy.wait(2000)
    cy.get('#components-button--primary-quiet-red')
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })

  //Primary Quiet Red Disabled
  it('Verify Primary Quiet Red Disabled Tab', function () {
    cy.Reload()
    cy.get('#components-button').should('be.visible').click({ force: true })
    cy.wait(2000)
    cy.get('#components-button--primary-quiet-red-disabled')
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })

  //Primary Quiet green
  it('Verify Primary Quiet Green Tab', function () {
    cy.Reload()
    cy.get('#components-button').should('be.visible').click({ force: true })
    cy.wait(2000)
    cy.get('#components-button--primary-quiet-green')
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })

  //Primary Quiet green Disabled
  it('Verify Primary Quiet Green Disabled Tab', function () {
    cy.Reload()
    cy.get('#components-button').should('be.visible').click({ force: true })
    cy.wait(2000)
    cy.get('#components-button--primary-quiet-green-disabled')
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })

  //Primary Gray with Prepend Icon
  it('Verify Primary Gray with Prepend Icon Tab', function () {
    cy.Reload()
    cy.get('#components-button').should('be.visible').click({ force: true })
    cy.wait(2000)
    cy.get('#components-button--primary-gray-with-prepend-icon')
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })

  //Primary Gray With Appended Icon
  it('Verify Primary Gray With Appended Icon Tab', function () {
    cy.Reload()
    cy.get('#components-button').should('be.visible').click({ force: true })
    cy.wait(2000)
    cy.get('#components-button--primary-gray-with-appended-icon')
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })

  //Primary Gray with Prepend and Appen Icon
  it('Verify Primary Gray with Prepend and Appen Icon Tab', function () {
    cy.Reload()
    cy.get('#components-button').should('be.visible').click({ force: true })
    cy.wait(2000)
    cy.get('#components-button--primary-gray-with-prepend-and-appen-icons')
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })

  //Primary Gray Icon Button Medium Tab
  it('Verify Primary Gray Icon Button Medium Tab', function () {
    cy.Reload()
    cy.get('#components-button').should('be.visible').click({ force: true })
    cy.wait(2000)
    cy.get('#components-button--primary-gray-icon-button-medium')
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })

  //Primary Gray Icon Button Small
  it('Verify Primary Gray Icon Button Small Tab', function () {
    cy.Reload()
    cy.get('#components-button')
      .scrollIntoView()
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
    cy.get('#components-button--primary-gray-icon-button-small')
      .scrollIntoView()
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })

  //Primary Gray Split Icon Button Medium right
  it('Verify Primary Gray Split Icon Button Medium right Tab', function () {
    cy.Reload()
    cy.xpath("//*[@id='components-button']")
      .scrollIntoView()
      .click({ force: true })
    cy.wait(2000)
    cy.xpath(
      "//*[@id='components-button--primary-gray-split-icon-button-medium-right']"
    )
      .scrollIntoView()
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })

  //Primary Gray Split Icon Button Medium left Tab
  it('Verify Primary Gray Split Icon Button Medium left Tab', function () {
    cy.Reload()
    cy.xpath("//*[@id='components-button']")
      .scrollIntoView()
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
    cy.get('#components-button--primary-gray-split-icon-button-medium-left')
      .scrollIntoView()
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })

  //Primary Gray Split Icon Button Small Right
  it('Verify Primary Gray Split Icon Button Small Right Tab', function () {
    cy.Reload()
    cy.xpath("//*[@id='components-button']")
      .scrollIntoView()
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
    cy.get('#components-button--primary-gray-split-icon-button-small-right')
      .scrollIntoView()
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })

  //Primary Gray Split Icon Button Small left
  it('Verify Gray Split Icon Button Small left Tab', function () {
    cy.Reload()
    cy.xpath("//*[@id='components-button']")
      .scrollIntoView()
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
    cy.get('#components-button--primary-gray-split-icon-button-small-left')
      .scrollIntoView()
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })

  //Default Button Full Width
  it('Verify Default Button Full Width Tab', function () {
    cy.Reload()
    cy.xpath("//*[@id='components-button']")
      .scrollIntoView()
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
    cy.get('#components-button--default-button-full-width')
      .scrollIntoView()
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })

  //Default Quiet Button Full Width
  it('Verify Default Quiet Button Full Width Tab', function () {
    cy.Reload()
    cy.xpath("//*[@id='components-button']")
      .scrollIntoView()
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
    cy.get('#components-button--default-quiet-button-full-width')
      .scrollIntoView()
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })

  //Default Button Disabled Full Width
  it('Verify Default Button Disabled Full Width Tab', function () {
    cy.Reload()
    cy.xpath("//*[@id='components-button']")
      .scrollIntoView()
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
    cy.get('#components-button--default-button-disabled-full-width')
      .scrollIntoView()
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })

  //Default Quiet Button Disabled Full Width
  it('Verify Default Quiet Button Disabled Full Width Tab', function () {
    cy.Reload()
    cy.xpath("//*[@id='components-button']")
      .scrollIntoView()
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
    cy.get('#components-button--default-quiet-button-disabled-full-width')
      .scrollIntoView()
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })

  //Primary Gray Full Width
  it('Verify Primary Gray Full Width Tab', function () {
    cy.Reload()
    cy.xpath("//*[@id='components-button']")
      .scrollIntoView()
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
    cy.get('#components-button--primary-gray-full-width')
      .scrollIntoView()
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })

  //Primary Gray Disabled Full Width
  it('Verify Primary Gray Disabled Full Width Tab', function () {
    cy.Reload()
    cy.xpath("//*[@id='components-button']")
      .scrollIntoView()
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
    cy.get('#components-button--primary-gray-disabled-full-width')
      .scrollIntoView()
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })

  //Primary Gray Loading
  it('Verify Primary Gray Loading Tab', function () {
    cy.Reload()
    cy.xpath("//*[@id='components-button']")
      .scrollIntoView()
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
    cy.get('#components-button--primary-gray-loading')
      .scrollIntoView()
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })

  //Primary Quiet Gray Loading
  it('Verify Primary Quiet Gray Loading Tab', function () {
    cy.Reload()
    cy.xpath("//*[@id='components-button']")
      .scrollIntoView()
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
    cy.get('#components-button--primary-quiet-gray-loading')
      .scrollIntoView()
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })

  //Primary Gray Loading Full Width
  it('Verify Primary Gray Loading Full Width Tab', function () {
    cy.Reload()
    cy.xpath("//*[@id='components-button']")
      .scrollIntoView()
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
    cy.get('#components-button--primary-gray-loading-full-width')
      .scrollIntoView()
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })

  //Primary Quiet Gray Loading Full Width
  it('Verify Primary Quiet Gray Loading Full Width Tab', function () {
    cy.Reload()
    cy.xpath("//*[@id='components-button']")
      .scrollIntoView()
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
    cy.get('#components-button--primary-quiet-gray-loading-full-width')
      .scrollIntoView()
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })

  //Green Button
  it('Verify Green Tab', function () {
    cy.Reload()
    cy.xpath("//*[@id='components-button']")
      .scrollIntoView()
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
    cy.get('#components-button--green')
      .scrollIntoView()
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })

  //Blue Button
  it('Verify Blue Tab', function () {
    cy.Reload()
    cy.xpath("//*[@id='components-button']")
      .scrollIntoView()
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
    cy.get('#components-button--blue')
      .scrollIntoView()
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })

  //Red Button
  it('Verify Red Tab', function () {
    cy.Reload()
    cy.xpath("//*[@id='components-button']")
      .scrollIntoView()
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
    cy.get('#components-button--blue')
      .scrollIntoView()
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })

  //Changed Label
  it('Verify Changed label Tab', function () {
    cy.Reload()
    cy.xpath("//*[@id='components-button']")
      .scrollIntoView()
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
    cy.get('#components-button--changed-label')
      .scrollIntoView()
      .should('be.visible')
      .click({ force: true })
    cy.wait(2000)
  })
})
