name: Cypress Tests

on: [push]
  # schedule:
  #  - cron:  "50 9 * * *"  # At every 6 minute    
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 
        
      - name: Cypress install
        uses: cypress-io/github-action@v6
        
      - name: Install NPM 
        run: npm install
        
      - name: Execute Cypress scripts
        run: npm start
